apiVersion: v1
kind: Service
metadata:
  name: iasc-elixir
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  # The port is not used by the service but it is needed to create SRV records for the statefulset
  - port: 80
  # Do not wait for the ready check
  publishNotReadyAddresses: true
  selector:
    app: iasc-elixir